### ISSUE TITLE
Add insertionPoints on Element when parsing templates inside dom modules

### ISSUE THREAD

**Issue by TimvdLippe** [Polymer/polymer-analyzer#391]
For https://github.com/Polymer/polymer-editor-service/pull/29 an enhancement that I could not implement yet was autocompletion for insertionPoints.

E.g.

```html
<template>
  <slot name="my-slot1"></slot>
  <slot name="my-slot2"></slot>
</template>
```

When analyzed by the analyzer returns in `Element` an array `insertionPoints`:
```js
insertionPoints: ['my-slot1', 'my-slot2']
```

**Comment by rictic** [comment]
We should definitely capture slots and their names, that's useful for lots of stuff, like documentation generation, and even autocompletion on slot names!

@blasten came up with something pretty great for element completion in the sublime plugin. He scans the element's documentation looking for the first block of code that uses the element and then he builds the autocompletion of the element based off of that.

So e.g. in [app-header-layout's documentation](https://github.com/PolymerElements/app-layout/blob/master/app-header-layout/app-header-layout.html#L21) there's this section

```html
<app-header-layout>
  <app-header fixed condenses effects="waterfall">
    <app-toolbar>
      <div main-title>App name</div>
    </app-toolbar>
  </app-header>
  <div>
    main content
  </div>
</app-header-layout>
```

[Emmanuel's code](https://github.com/Polymer/polymer-sublime-plugin/pull/1/files#diff-57ca5c25be86165da3a6c470ace95ac0R134) extracts that, and uses it to autocomplete app-header-layout to that code snippet, which turns out to be really useful!

**Comment by TimvdLippe** [comment]
That's a cool idea! I do think there are valid usecases for this, but for most elements with insertion points there can be a Cartesian product possible combinations. For now @blasten workaround does the job!

**Comment by rictic** [comment]
Yeah, I think we'll definitely want both, and we can experiment with when to do which.
