### ISSUE TITLE
Extend the `Analyzer#_fork()` API to support replacing the `urlLoader` option (possibly replace any of the initialization options?)

### ISSUE THREAD

**Issue by usergenic** [Polymer/polymer-analyzer#547]
The primary impetus for adding `_fork` method to Analyzer was to support use of a different `UrlLoader` downstream during `polymer-build` pipeline so the bundle operation would read from the stream at that point instead of from the original analysis documents (to support bundling of minified or other transpiled script/sass sources etc.).

Unfortunately, the private `urlLoader` property is on a private AnalysisContext within the Analyzer, so there's no means to replace it after the fork.  It makes sense to replace during the fork operation itself though, so if `_fork()` could take similar/identical arguments similar to the way Analyzer constructor does, it would be a predictable interface and solve this.

**Comment by rictic** [comment]
It might be valuable to be able to pass in new initialization options to `_fork`. e.g. someone might want to add new scanners. The Analyzer can determine what caches need to be emptied based on the changed options. Related, but it would also be useful in these scenarios to be able to read the configuration off of an existing Analyzer.

e.g. a lint rule could necessitate additional scanners. By forking rather than creating a new analyzer we could reuse the other configuration options from the analyzer passed into the linter, as well as reusing the pre-scan caches (i.e. the loading and parsing caches).

**Comment by usergenic** [comment]
Done.
