### ISSUE TITLE
Mix mixins into mixins

### ISSUE THREAD

**Issue by rictic** [Polymer/polymer-analyzer#564]
Currently ElementMixin has its own array of mixins, but those mixins aren't mixed into the ElementMixin. i.e. if A and B are mixins, and A includes B, A won't directly include B's properties, methods etc, unlike Elements. This is counterintuitive, and makes it harder to work with mixins. We should make them more like Elements in this respect.

**Comment by arthurevans** [comment]
This also means that almost none of the methods and properties in Polymer.Element are actually documented, since most of them come in through multiple levels of mixins. 

I'd be inclined to bump the priority up on this one since it's a regression compared to 1.x in the amount of coverage we have on the most-used API reference.
