### ISSUE TITLE
Results filtered out

### ISSUE THREAD

**Issue by samuelli** [Polymer/polymer-analyzer#606]
Looks like the data is being filtered out. For wc.org we use the bower main file to analyze. This file typically imports the rest of the elements that are used.
```bash
$ polymer --version
0.18.0-pre.15
$  git clone https://github.com/PolymerElements/app-layout
$ cd app-layout
$ polymer analyze app-layout.html
{
  "schema_version": "1.0.0"
}
$ polymer analyze
<33 elements>
```

**Comment by samuelli** [comment]
Is it preferred to:
 * use listed main files (as we were doing in hydrolysis)
 * analyze on the package level & filter by path?

cc @rictic @justinfagnani

**Comment by justinfagnani** [comment]
This is interesting, I wouldn't expect everything to be filtered out in this case. I'll look at that.

Even so, analyzePackage() is probably the way to go. This is at least its intended usage. I'd be interested if it isn't working for some reason.

**Comment by rictic** [comment]
The issue is that `app-layout.html` does not define any elements, it just contains imports. The current semantics of `polymer analyze $inputFile` are to describe those features which are defined directly in `$inputFile`.

Maybe that's not helpful? But it'd be tricky to figure out exactly what you mean that didn't more or less turn into analyze package.

**Comment by justinfagnani** [comment]
ah right, so `analyzePackage()` for now and we can add flags for pulling in imported and external features.

**Comment by samuelli** [comment]
Fair, I'll switch to using analyze package. Can probably close this.

**Comment by rictic** [comment]
SGTM
