### ISSUE TITLE
Move typescript dependency from 'dependencies' to 'devDependencies'

### ISSUE THREAD

**Issue by freshp86** [Polymer/polymer-analyzer#697]
Currently typescript is declared inside package.json [dependencies](), which causes an additional 26MB of dependencies to be downloaded when running `npm install polymer-bundler`.

I believe that all the [@types dependencies](https://github.com/Polymer/polymer-analyzer/blob/master/package.json#L66-L74) can also be moved. This is affecting Chromium's effort to [migrate](https://bugs.chromium.org/p/chromium/issues/detail?id=731881) from Vulcanize to polymer-bundler

cc @usergenic

**Comment by usergenic** [comment]
The team has discussed and agreed we can remove typescript as prod dependency for now, but many of other `@types` are transacted in as part of the public interface to Analyzer, for the time being, we are providing type definitions in our npm packages as a matter of course instead of making them external.  We may revisit that choice in the future, but for now I think we should expect they remain.  Their filesize of course represents a small fraction of typescript's size.

**Comment by freshp86** [comment]
Any updates on this?

**Comment by freshp86** [comment]
cc @azakus @kevinpschaaf

**Comment by usergenic** [comment]
I expect we will be able to release an update to polymer-analyzer without
typescript by tomorrow or wednesday (because of the holiday)

**Comment by usergenic** [comment]
#702 merged.  Need to release still, but closing issue as fixed.
