### ISSUE TITLE
Polymer Element public API shouldn't be in custom elements extending Polymer.Element

### ISSUE THREAD

**Issue by manolo** [Polymer/polymer-analyzer#717]
When you have an custom element extending Polymer.Element, all public API of polymer is shown.

```
class KkElement extends Polymer.Element {
...
```

Otherwise, if your custom element extends a mixin, Polymer API is not listed.

```
  /**
   * @polymerMixin
   */
  Foo = superClass => class FooMixin extends superClass {
  };

  class KkElement extends Foo(Polymer.Element) {
  ...
```

Related with https://github.com/PolymerElements/iron-component-page/issues/147

**Comment by limonte** [comment]
![a41](https://user-images.githubusercontent.com/6059356/32267030-7c9f83c0-bef2-11e7-805f-b778885f92e1.png)

**Comment by YuriyVaadin** [comment]
It is possible to use a workaround until proper solution will be implemented.
Workaround: `class SomeElement extends (class extends Polymer.Element {})`

**Comment by mgibas** [comment]
I dont see this behavior after removing `@extends Polymer.Element` from jsdoc... not sure its a valid thing to do though

**Comment by rictic** [comment]
This should be solved in iron-component-page, perhaps by hiding inherited properties by default, or otherwise downplaying them.

From a static analysis perspective, if `Foo` extends `Bar`, then `Foo`'s also inherits `Bar`'s public API. The reason adding a mixin removes those entries from your iron-component-page results is that mixins currently defeat polymer-analyzer's analysis, but that shouldn't be relied upon.
